name: jop_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  dots_indicator: ^4.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  get: ^4.7.2
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^11.4.0
  pinput: ^5.0.1
  provider: ^6.1.2
  share_plus: ^10.1.4
  shared_preferences: ^2.2.2
  syncfusion_flutter_pdfviewer: ^24.2.9
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Light.ttf
        - asset: assets/fonts/Mulish-SemiBold.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
